### ISSUE TITLE
Uploading to Heroku with sbt-sass fails

### ISSUE THREAD

**Issue by W0lfbane** [madoushi/sbt-sass#5]
I am trying to upload a Play 2.4 project to heroku, which uses this plugin. I am using two buildpacks on heroku, in the following order: heroku/ruby, heroku/scala.

When trying to upload to heroku, I get this error: 

```
remote:        org.madoushi.sbt.sass.SassCompilerException: /tmp/scala_buildpack_build_dir/vendor/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
remote:         from /tmp/scala_buildpack_build_dir/vendor/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote:         from /tmp/scala_buildpack_build_dir/vendor/bundle/bin/sass:14:in `<main>'
remote:         at org.madoushi.sbt.sass.SassCompiler$.runCommand(SassCompiler.scala:92)
remote:         at org.madoushi.sbt.sass.SassCompiler$.compile(SassCompiler.scala:48)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5$$anonfun$6$$anonfun$7.apply(SbtSass.scala:61)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5$$anonfun$6$$anonfun$7.apply(SbtSass.scala:49)
remote:         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
remote:         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
remote:         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
remote:         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
remote:         at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
remote:         at scala.collection.AbstractTraversable.map(Traversable.scala:105)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5$$anonfun$6.apply(SbtSass.scala:49)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5$$anonfun$6.apply(SbtSass.scala:45)
remote:         at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5.apply(SbtSass.scala:44)
remote:         at org.madoushi.sbt.sass.SbtSass$$anonfun$5.apply(SbtSass.scala:39)
remote:         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
remote:         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
remote:         at sbt.std.Transform$$anon$4.work(System.scala:63)
remote:         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
remote:         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
remote:         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
remote:         at sbt.Execute.work(Execute.scala:235)
remote:         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
remote:         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
remote:         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
remote:         at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
remote:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
remote:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
remote:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
remote:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
remote:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
remote:         at java.lang.Thread.run(Thread.java:745)
remote:        [error] (web-assets:sass) org.madoushi.sbt.sass.SassCompilerException: /tmp/scala_buildpack_build_dir/vendor/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
remote:        [error]  from /tmp/scala_buildpack_build_dir/vendor/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote:        [error]  from /tmp/scala_buildpack_build_dir/vendor/bundle/bin/sass:14:in `<main>'
remote:        [error] Total time: 33 s, completed May 5, 2016 10:27:30 PM
remote: 
remote:  !     ERROR: Failed to run sbt!
remote:        We're sorry this build is failing. If you can't find the issue in application
remote:        code, please submit a ticket so we can help: https://help.heroku.com
remote:        You can also try reverting to the previous version of the buildpack by running:
remote:        $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala#previous-version
remote:        
remote:        Thanks,
remote:        Heroku
remote: 
remote: 
remote:  !     Push rejected, failed to compile Play 2.x - Scala app
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to vetpros-stage.
```

Any idea how this can be resolved?

**Comment by jan0sch** [comment]
I guess that this is related to the fact that you need a ruby gem (sass) for the sbt plugin. Maybe you should try out the [sbt-sassify plugin](https://github.com/irundaia/sbt-sassify) which is meanwhile the recommended plugin by the play folks.

**Comment by W0lfbane** [comment]
I forgot to mention, there is a Gemfile in my project which gets the Ruby gem with bundle. No clue why this was happening,, the gem downloads fine, couldn't for the life of me figure it out. I will try your suggestions though, thank you!
